package com.example.demo.dao;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cus_id
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    private Integer cusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.username
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.acno
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    private String acno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.gender
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public Customer(Integer cusId, String username, String acno, String gender, String phone) {
        this.cusId = cusId;
        this.username = username;
        this.acno = acno;
        this.gender = gender;
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public Customer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cus_id
     *
     * @return the value of customer.cus_id
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public Integer getCusId() {
        return cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cus_id
     *
     * @param cusId the value for customer.cus_id
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public void setCusId(Integer cusId) {
        this.cusId = cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.username
     *
     * @return the value of customer.username
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.username
     *
     * @param username the value for customer.username
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.acno
     *
     * @return the value of customer.acno
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public String getAcno() {
        return acno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.acno
     *
     * @param acno the value for customer.acno
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public void setAcno(String acno) {
        this.acno = acno == null ? null : acno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.gender
     *
     * @return the value of customer.gender
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.gender
     *
     * @param gender the value for customer.gender
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone
     *
     * @return the value of customer.phone
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone
     *
     * @param phone the value for customer.phone
     *
     * @mbggenerated Mon Dec 10 10:22:05 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}